# Generated by Django 4.1.2 on 2025-03-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_th', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.JSONField(default=list)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('cast', models.JSONField(default=list)),
                ('watch_platforms', models.JSONField(default=dict)),
                ('content_type', models.CharField(choices=[('Movie', 'Movie'), ('TV Series', 'TV Series')], max_length=50)),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=list)),
                ('history', models.JSONField(default=list)),
                ('is_first_login', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
